// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pvz-service/v1/pvz_service.proto

package pvz_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PvzService_GiveOrders_FullMethodName        = "/pvz.PvzService/GiveOrders"
	PvzService_GetCustomerOrders_FullMethodName = "/pvz.PvzService/GetCustomerOrders"
	PvzService_ReceiveOrder_FullMethodName      = "/pvz.PvzService/ReceiveOrder"
	PvzService_RemoveOrder_FullMethodName       = "/pvz.PvzService/RemoveOrder"
	PvzService_ReturnOrder_FullMethodName       = "/pvz.PvzService/ReturnOrder"
	PvzService_GetReturnedOrders_FullMethodName = "/pvz.PvzService/GetReturnedOrders"
)

// PvzServiceClient is the client API for PvzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PvzServiceClient interface {
	GiveOrders(ctx context.Context, in *GiveOrdersRequest, opts ...grpc.CallOption) (*GiveOrdersResponse, error)
	GetCustomerOrders(ctx context.Context, in *GetCustomerOrdersRequest, opts ...grpc.CallOption) (*GetCustomerOrdersResponse, error)
	ReceiveOrder(ctx context.Context, in *ReceiveOrderRequest, opts ...grpc.CallOption) (*ReceiveOrderResponse, error)
	RemoveOrder(ctx context.Context, in *RemoveOrderRequest, opts ...grpc.CallOption) (*RemoveOrderResponse, error)
	ReturnOrder(ctx context.Context, in *ReturnOrderRequest, opts ...grpc.CallOption) (*ReturnOrderResponse, error)
	GetReturnedOrders(ctx context.Context, in *GetReturnedOrdersRequest, opts ...grpc.CallOption) (*GetReturnedOrdersResponse, error)
}

type pvzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPvzServiceClient(cc grpc.ClientConnInterface) PvzServiceClient {
	return &pvzServiceClient{cc}
}

func (c *pvzServiceClient) GiveOrders(ctx context.Context, in *GiveOrdersRequest, opts ...grpc.CallOption) (*GiveOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GiveOrdersResponse)
	err := c.cc.Invoke(ctx, PvzService_GiveOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pvzServiceClient) GetCustomerOrders(ctx context.Context, in *GetCustomerOrdersRequest, opts ...grpc.CallOption) (*GetCustomerOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerOrdersResponse)
	err := c.cc.Invoke(ctx, PvzService_GetCustomerOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pvzServiceClient) ReceiveOrder(ctx context.Context, in *ReceiveOrderRequest, opts ...grpc.CallOption) (*ReceiveOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveOrderResponse)
	err := c.cc.Invoke(ctx, PvzService_ReceiveOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pvzServiceClient) RemoveOrder(ctx context.Context, in *RemoveOrderRequest, opts ...grpc.CallOption) (*RemoveOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveOrderResponse)
	err := c.cc.Invoke(ctx, PvzService_RemoveOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pvzServiceClient) ReturnOrder(ctx context.Context, in *ReturnOrderRequest, opts ...grpc.CallOption) (*ReturnOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnOrderResponse)
	err := c.cc.Invoke(ctx, PvzService_ReturnOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pvzServiceClient) GetReturnedOrders(ctx context.Context, in *GetReturnedOrdersRequest, opts ...grpc.CallOption) (*GetReturnedOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReturnedOrdersResponse)
	err := c.cc.Invoke(ctx, PvzService_GetReturnedOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PvzServiceServer is the server API for PvzService service.
// All implementations must embed UnimplementedPvzServiceServer
// for forward compatibility.
type PvzServiceServer interface {
	GiveOrders(context.Context, *GiveOrdersRequest) (*GiveOrdersResponse, error)
	GetCustomerOrders(context.Context, *GetCustomerOrdersRequest) (*GetCustomerOrdersResponse, error)
	ReceiveOrder(context.Context, *ReceiveOrderRequest) (*ReceiveOrderResponse, error)
	RemoveOrder(context.Context, *RemoveOrderRequest) (*RemoveOrderResponse, error)
	ReturnOrder(context.Context, *ReturnOrderRequest) (*ReturnOrderResponse, error)
	GetReturnedOrders(context.Context, *GetReturnedOrdersRequest) (*GetReturnedOrdersResponse, error)
	mustEmbedUnimplementedPvzServiceServer()
}

// UnimplementedPvzServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPvzServiceServer struct{}

func (UnimplementedPvzServiceServer) GiveOrders(context.Context, *GiveOrdersRequest) (*GiveOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveOrders not implemented")
}
func (UnimplementedPvzServiceServer) GetCustomerOrders(context.Context, *GetCustomerOrdersRequest) (*GetCustomerOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerOrders not implemented")
}
func (UnimplementedPvzServiceServer) ReceiveOrder(context.Context, *ReceiveOrderRequest) (*ReceiveOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveOrder not implemented")
}
func (UnimplementedPvzServiceServer) RemoveOrder(context.Context, *RemoveOrderRequest) (*RemoveOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveOrder not implemented")
}
func (UnimplementedPvzServiceServer) ReturnOrder(context.Context, *ReturnOrderRequest) (*ReturnOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnOrder not implemented")
}
func (UnimplementedPvzServiceServer) GetReturnedOrders(context.Context, *GetReturnedOrdersRequest) (*GetReturnedOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReturnedOrders not implemented")
}
func (UnimplementedPvzServiceServer) mustEmbedUnimplementedPvzServiceServer() {}
func (UnimplementedPvzServiceServer) testEmbeddedByValue()                    {}

// UnsafePvzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PvzServiceServer will
// result in compilation errors.
type UnsafePvzServiceServer interface {
	mustEmbedUnimplementedPvzServiceServer()
}

func RegisterPvzServiceServer(s grpc.ServiceRegistrar, srv PvzServiceServer) {
	// If the following call pancis, it indicates UnimplementedPvzServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PvzService_ServiceDesc, srv)
}

func _PvzService_GiveOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GiveOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvzServiceServer).GiveOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvzService_GiveOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvzServiceServer).GiveOrders(ctx, req.(*GiveOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PvzService_GetCustomerOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvzServiceServer).GetCustomerOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvzService_GetCustomerOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvzServiceServer).GetCustomerOrders(ctx, req.(*GetCustomerOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PvzService_ReceiveOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvzServiceServer).ReceiveOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvzService_ReceiveOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvzServiceServer).ReceiveOrder(ctx, req.(*ReceiveOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PvzService_RemoveOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvzServiceServer).RemoveOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvzService_RemoveOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvzServiceServer).RemoveOrder(ctx, req.(*RemoveOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PvzService_ReturnOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvzServiceServer).ReturnOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvzService_ReturnOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvzServiceServer).ReturnOrder(ctx, req.(*ReturnOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PvzService_GetReturnedOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReturnedOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvzServiceServer).GetReturnedOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvzService_GetReturnedOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvzServiceServer).GetReturnedOrders(ctx, req.(*GetReturnedOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PvzService_ServiceDesc is the grpc.ServiceDesc for PvzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PvzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pvz.PvzService",
	HandlerType: (*PvzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GiveOrders",
			Handler:    _PvzService_GiveOrders_Handler,
		},
		{
			MethodName: "GetCustomerOrders",
			Handler:    _PvzService_GetCustomerOrders_Handler,
		},
		{
			MethodName: "ReceiveOrder",
			Handler:    _PvzService_ReceiveOrder_Handler,
		},
		{
			MethodName: "RemoveOrder",
			Handler:    _PvzService_RemoveOrder_Handler,
		},
		{
			MethodName: "ReturnOrder",
			Handler:    _PvzService_ReturnOrder_Handler,
		},
		{
			MethodName: "GetReturnedOrders",
			Handler:    _PvzService_GetReturnedOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pvz-service/v1/pvz_service.proto",
}
