grpc:
  host: "localhost:7001"

db:
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5433"
  dbname: "postgres"
  sslmode: "disable"

kafka_logger:
  brokers:
    - "localhost:9092"
  topic: "pvz.events-log"
  methods:
    - "ReceiveOrder"
    - "GiveOrders"
    - "ReturnOrder"
